version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: ./deploy/backend/Dockerfile
      target: dev
    container_name: fastapi
    image: farm-template:backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:80
    environment:
      LOG_LEVEL: 'DEBUG'
      RELOAD: 'true'
    env_file:
      - ./backend/.env

  react:
    build:
      context: .
      dockerfile: ./deploy/frontend/Dockerfile
      target: dev
    container_name: react
    image: nakama-ui:frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    environment:
      GENERATE_SOURCEMAP: "false"   # https://github.com/facebook/create-react-app/pull/11752
    env_file:
     - ./frontend/.env

volumes:
  minio_volume: {}
  mongodb: {}