version: '3.9'

services:
  react:
    build:
      context: .
      dockerfile: ./deploy/frontend/Dockerfile
      target: dev
    container_name: react
    image: nakama-ui:frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    environment:
      GENERATE_SOURCEMAP: "false"   # https://github.com/facebook/create-react-app/pull/11752
      
volumes:
  mongodb: {}