version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/

  fastapi:
    build:
      context: .
      dockerfile: ./deploy/backend/Dockerfile
      target: dev
    container_name: fastapi
    volumes:
      - ./backend:/app
    ports:
      - 8000:80
    environment:
      RELOAD: 'true'
      MONGODB_HOST: mongo
      MONGODB_PORT: '27017'
      MONGODB_USER: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
      
  nginx:
    build:
      context: .
      dockerfile: ./deploy/frontend/Dockerfile
      target: production
    container_name: nginx
    ports:
      - 3000:3000

volumes:
  mongodb: {}