version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: ./deploy/backend/Dockerfile
      target: deploy
    container_name: fastapi
    image: jasoncky96/nakama-backend:latest
    ports:
      - 8000:80
    environment:
      LOG_LEVEL: 'DEBUG'
      RELOAD: 'true'
    env_file:
      - ./backend/.env

  react:
    build:
      context: .
      dockerfile: ./deploy/frontend/Dockerfile
      target: production
    container_name: react
    image: jasoncky96/nakama-frontend:latest
    ports:
      - 3000:3000

volumes:
  minio_volume: {}
  mongodb: {}