apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nakama-backend
  name: nakama-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nakama-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nakama-backend
    spec:
      containers:
      - image: jasoncky96/nakama-backend:latest
        imagePullPolicy: Always
        name: nakama-backend
        resources: {}
        env:
        - name: APP_NAME
          value: backend_api
        - name: APP_VERSION
          value: "0.1"
        - name: SLEEP_DELAY
          value: "0.5"
        - name: LOG_LEVEL
          value: 'INFO'
        - name: RELOAD
          value: 'false'
        - name: CLIENT_ID
          value: 'fill-this-in'
        - name: CLIENT_SECRET
          value: 'fill-this-in'
        - name: GITLAB_TOKEN_URL
          value: 'https://gitlab.com/oauth/token'
        ports:
          - containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nakama-backend
  name: nakama-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nakama-backend


