apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: farm-template
    component: frontend
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: farm-template
    component: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: farm-template
    component: frontend
  name: farm-template-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: farm-template
      component: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: farm-template
        component: frontend
    spec:
      containers:
      - image: farm-template:frontend
        name: farm-template-frontend
        resources:
          requests:
            cpu: 200m
            memory: 500m
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
          - containerPort: 3000
            name: http
            protocol: TCP

